class ThongKeDauTu:
    def __init__(self, TONGVONDAUTU_FDI, TONGVONDAUTU_VN, SOLUONG_FDI, SOLUONG_VN):
        self.TONGVONDAUTU_FDI = TONGVONDAUTU_FDI
        self.TONGVONDAUTU_VN = TONGVONDAUTU_VN
        self.SOLUONG_FDI = SOLUONG_FDI
        self.SOLUONG_VN = SOLUONG_VN